-- Migration: 0002_seed_words.sql
-- JLPT N5 Seed Data (60 core words)
INSERT INTO words (kanji, romaji, romaji_numbered, kana, meaning_mn, meaning_en, jlpt_level, part_of_speech, example_jp, example_romaji, example_mn, stroke_count) VALUES
-- JLPT N5: Greetings & Basics
('こんにちは','konnichiwa','konnichiwa','こんにちは','Сайн уу (өдрийн мэнд)','Hello (daytime)',1,'phrase','こんにちは、わたしはリーです。','Konnichiwa, watashi wa Rii desu.','Сайн уу, намайг Ли гэдэг.',0),
('ありがとう','arigatou','arigatou','ありがとう','Баярлалаа','Thank you',1,'phrase','ありがとうございます。','Arigatou gozaimasu.','Баярлалаа (дэлгэрэнгүй).',0),
('さようなら','sayounara','sayounara','さようなら','Баяртай','Goodbye',1,'phrase','さようなら、また明日。','Sayounara, mata ashita.','Баяртай, маргааш уулзъя.',0),
('わたし','watashi','watashi','わたし','Би','I/Me',1,'pronoun','わたしは学生です。','Watashi wa gakusei desu.','Би оюутан.',0),
('あなた','anata','anata','あなた','Чи/Та','You',1,'pronoun','あなたの名前は何ですか？','Anata no namae wa nan desu ka?','Таны нэр хэн бэ?',0),
('かれ','kare','kare','かれ','Тэр (эр)','He',1,'pronoun','かれは先生です。','Kare wa sensei desu.','Тэр багш.',0),
('かのじょ','kanojo','kanojo','かのじょ','Тэр (эм)','She',1,'pronoun','かのじょはきれいです。','Kanojo wa kirei desu.','Тэр үзэсгэлэнтэй.',0),
('です','desu','desu','です','Байна (дэлгэрэнгүй)','To be (polite)',1,'verb','これはペンです。','Kore wa pen desu.','Энэ бол үзэг.',0),
('じゃない','ja nai','ja nai','じゃない','Биш','Not (informal)',1,'phrase','これはペンじゃない。','Kore wa pen ja nai.','Энэ үзэг биш.',0),
('いい','ii','ii','いい','Сайн/Зөв','Good',1,'adjective','今日はいい天気ですね。','Kyou wa ii tenki desu ne.','Өнөөдөр цаг агаар сайн байна.',0),
-- Adjectives
('おおきい','ookii','ookii','おおきい','Том','Big',1,'adjective','このりんごはおおきいです。','Kono ringo wa ookii desu.','Энэ алим том.',0),
('ちいさい','chiisai','chiisai','ちいさい','Жижиг','Small',1,'adjective','このねこはちいさいです。','Kono neko wa chiisai desu.','Энэ муур жижиг.',0),
-- People & Society
('ひと','hito','hito','ひと','Хүн','Person',1,'noun','あのひとはだれですか？','Ano hito wa dare desu ka?','Тэр хүн хэн бэ?',0),
('にほん','nihon','nihon','にほん','Япон','Japan',1,'noun','わたしはにほんから来ました。','Watashi wa nihon kara kimashita.','Би Японоос ирсэн.',0),
('がくせい','gakusei','gakusei','がくせい','Оюутан','Student',1,'noun','わたしは大学生です。','Watashi wa daigakusei desu.','Би их сургуулийн оюутан.',0),
('せんせい','sensei','sensei','せんせい','Багш','Teacher',1,'noun','わたしのせんせいはやさしいです。','Watashi no sensei wa yasashii desu.','Миний багш эелдэг.',0),
-- Numbers
('いち','ichi','ichi','いち','Нэг','One',1,'number','いち、に、さん。','Ichi, ni, san.','Нэг, хоёр, гурав.',0),
('に','ni','ni','に','Хоёр','Two',1,'number','にほんごのにつのもじ。','Nihongo no ni tsu no moji.','Японы хоёр тэмдэгт.',0),
('さん','san','san','さん','Гурав','Three',1,'number','さんにんのともだち。','San nin no tomodachi.','Гурван найз.',0),
-- Verbs
('たべる','taberu','taberu','たべる','Идэх','Eat',1,'verb','わたしはすしをたべます。','Watashi wa sushi o tabemasu.','Би суши иднэ.',0),
('のむ','nomu','nomu','のむ','Уух','Drink',1,'verb','おちゃをのみます。','Ocha o nomimasu.','Цай уунам.',0),
('くる','kuru','kuru','くる','Ирэх','Come',1,'verb','ともだちがきます。','Tomodachi ga kimasu.','Найз ирнэ.',0),
('いく','iku','iku','いく','Явах','Go',1,'verb','がっこうにいきます。','Gakkou ni ikimasu.','Сургуульд явна.',0),
('みる','miru','miru','みる','Харах/Үзэх','Look/Watch',1,'verb','テレビをみます。','Terebi o mimasu.','Телевиз үзнэ.',0),
('はなす','hanasu','hanasu','はなす','Ярих','Speak',1,'verb','にほんごをはなします。','Nihongo o hanashimasu.','Япон хэлээр ярьдаг.',0),
-- JLPT N4: Conjunctions & Adverbs
('なぜなら','nazenara','nazenara','なぜなら','Учир нь','Because',2,'conjunction','あめだから、いえにいます。','Ame dakara, ie ni imasu.','Бороо орсон учир гэртээ байна.',0),
('だから','dakara','dakara','だから','Тийм учир','Therefore',2,'conjunction','つかれた、だからねます。','Tsukareta, dakara nemasu.','Ядарсан учир унтна.',0),
('でも','demo','demo','でも','Гэхдээ','But/However',2,'conjunction','いきたい、でもじかんがない。','Ikitai, demo jikan ga nai.','Явмаар боловч цаг байхгүй.',0),
('もし','moshi','moshi','もし','Хэрвээ','If',2,'conjunction','もしきたら、うれしいです。','Moshi kitara, ureshii desu.','Хэрвээ ирвэл баяртай байна.',0),
('もう','mou','mou','もう','Аль хэдийн','Already',2,'adverb','もうたべました。','Mou tabemashita.','Аль хэдийн идэчихсэн.',0),
('まだ','mada','mada','まだ','Дахиад/Бас','Still/Yet',2,'adverb','まだたべています。','Mada tabete imasu.','Дахиад идэж байна.',0),
('おもう','omou','omou','おもう','Бодох','Think/Feel',2,'verb','かれがただしいとおもいます。','Kare ga tadashii to omoimasu.','Тэр зөв гэж бодож байна.',0),
('しる','shiru','shiru','しる','Мэдэх','Know',2,'verb','あなたのなまえをしっています。','Anata no namae wo shitte imasu.','Таны нэрийг мэдэж байна.',0),
('のぞむ','nozomu','nozomu','のぞむ','Найдах','Hope/Wish',2,'verb','あしたてんきがいいとのぞみます。','Ashita tenki ga ii to nozomimasu.','Маргааш цаг агаар сайн байгаасай гэж найдана.',0),
('たすける','tasukeru','tasukeru','たすける','Туслах','Help',2,'verb','わたしをたすけてください。','Watashi o tasukete kudasai.','Надад тусална уу.',0),
('れんしゅう','renshuu','renshuu','れんしゅう','Дасгал хийх','Practice',2,'noun','まいにちにほんごをれんしゅうします。','Mainichi nihongo o renshuu shimasu.','Өдөр бүр Японы хэл дасгалладаг.',0),
('がんばる','ganbaru','ganbaru','がんばる','Хичээх','Work hard',2,'verb','もっとがんばります。','Motto ganbarimasu.','Илүү хичээнэ.',0),
('たいせつ','taisetsu','taisetsu','たいせつ','Чухал','Important',2,'adjective','けんこうはたいせつです。','Kenkou wa taisetsu desu.','Эрүүл мэнд чухал.',0),
('しずか','shizuka','shizuka','しずか','Тайван','Quiet',2,'adjective','としょかんはしずかです。','Toshokan wa shizuka desu.','Номын сан тайван.',0),
('うれしい','ureshii','ureshii','うれしい','Баяртай','Happy',2,'adjective','きょうはうれしいです。','Kyou wa ureshii desu.','Өнөөдөр баяртай байна.',0),
-- JLPT N3
('けれども','keredomo','keredomo','けれども','Хэдийгээр','Although',3,'conjunction','つかれた、けれどもたのしい。','Tsukareta, keredomo tanoshii.','Ядарсан ч гэсэн тааламжтай.',0),
('そして','soshite','soshite','そして','Мөн түүнчлэн','Moreover',3,'conjunction','かれはかしこい、そしてはたらきもの。','Kare wa kashikoi, soshite hatarakimono.','Тэр ухаантай, мөн хичээнгүй.',0),
('だけでなく','dake de naku','dake de naku','だけでなく','Зөвхөн...биш','Not only',3,'conjunction','はなすだけでなく、かけます。','Hanasu dake de naku, kakemasu.','Зөвхөн ярьж биш, бичиж чаддаг.',0),
('ながら','nagara','nagara','ながら','Нэгэн зэрэг','While doing',3,'adverb','たべながらほんをよみます。','Tabenagara hon o yomimasu.','Идэж байхдаа ном уншина.',0),
('ついに','tsui ni','tsui ni','ついに','Эцэст нь','Finally',3,'adverb','ついにおわりました！','Tsui ni owarimashita!','Эцэст нь дуусгалаа!',0),
('つづける','tsuzukeru','tsuzukeru','つづける','Үргэлжлүүлэх','Continue',3,'verb','はなしをつづけてください。','Hanashi o tsuzukete kudasai.','Үргэлжлүүлэн ярьна уу.',0),
('せつめいする','setsumei suru','setsumei suru','せつめいする','Тайлбарлах','Explain',3,'verb','せつめいしてもらえますか？','Setsumei shite moraemasu ka?','Тайлбарлаж өгч чадах уу?',0),
('ていあんする','teian suru','teian suru','ていあんする','Санал болгох','Suggest',3,'verb','やすむことをていあんします。','Yasumu koto o teian shimasu.','Амрахыг санал болгоно.',0),
('かんしゃする','kansha suru','kansha suru','かんしゃする','Талархах','Grateful',3,'verb','たすけてくれてかんしゃします。','Tasukete kurete kansha shimasu.','Тусалсанд талархаж байна.',0),
('しんぱいする','shinpai suru','shinpai suru','しんぱいする','Санаа зовох','Worry',3,'verb','しんぱいしないで。','Shinpai shinai de.','Санаа зовох хэрэггүй.',0),
('みつける','mitsukeru','mitsukeru','みつける','Олох/Нээх','Discover',3,'verb','もんだいをみつけました。','Mondai o mitsukemashita.','Асуудал олж илрүүллээ.',0),
('かんがえる','kangaeru','kangaeru','かんがえる','Бодох','Think/Believe',3,'verb','このほうほうがいいとかんがえます。','Kono houhou ga ii to kangaemasu.','Энэ арга сайн гэж бодно.',0),
('えいきょうする','eikyou suru','eikyou suru','えいきょうする','Нөлөөлөх','Influence',3,'verb','てんきはきぶんにえいきょうします。','Tenki wa kibun ni eikyou shimasu.','Цаг агаар сэтгэлд нөлөөлнө.',0),
('かんせいする','kansei suru','kansei suru','かんせいする','Дуусгах','Complete',3,'verb','しゅくだいをかんせいしました。','Shukudai o kansei shimashita.','Даалгавраа дуусгалаа.',0),
('あげる','ageru','ageru','あげる','Дээшлүүлэх','Improve',3,'verb','にほんごをあげたいです。','Nihongo o agetai desu.','Японы хэлээ дээшлүүлмээр байна.',0);
