-- Generated: 0016_mock_exam_seed.sql
-- Template 1: HSK 1 模拟考试 — 1-р mock шалгалт

INSERT INTO exam_templates (id,title,hsk_level,total_questions,duration_minutes,passing_score,max_score,is_published)
VALUES (1,'HSK 1 模拟考试 — 1-р mock шалгалт',1,40,35,120,200,1);

INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',1,1,'picture_match','我喜欢喝茶。','Цай уух дуртай хүн','','["true","false"]','true',1);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',1,2,'picture_match','他在看书。','Хоол хийж байгаа хүн','','["true","false"]','false',2);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',1,3,'picture_match','今天下雨了。','Бороо орж байна','','["true","false"]','true',3);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',1,4,'picture_match','她是医生。','Багш','','["true","false"]','false',4);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',1,5,'picture_match','我有一只猫。','Муур','','["true","false"]','true',5);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',2,6,'sentence_picture','我想吃苹果。','','','["Алим","Ном","Ус","Цай"]','Алим',6);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',2,7,'sentence_picture','他坐飞机去北京。','','','["Онгоц","Галт тэрэг","Такси","Машин"]','Онгоц',7);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',2,8,'sentence_picture','现在三点了。','','','["3:00","5:00","7:00","9:00"]','3:00',8);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',2,9,'sentence_picture','她在学校学习。','','','["Сургууль","Эмнэлэг","Дэлгүүр","Гэр"]','Сургууль',9);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',2,10,'sentence_picture','我买了一些水果。','','','["Жимс","Хувцас","Ном","Ус"]','Жимс',10);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',3,11,'dialogue_picture','A: 你想喝什么？ B: 我想喝茶。','','','["Цай","Ус","Кофе","Сүү"]','Цай',11);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',3,12,'dialogue_picture','A: 今天天气怎么样？ B: 今天很热。','','','["Халуун нар","Бороо","Цас","Хүйтэн"]','Халуун нар',12);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',3,13,'dialogue_picture','A: 你去哪儿？ B: 我去医院。','','','["Эмнэлэг","Сургууль","Дэлгүэр","Гэр"]','Эмнэлэг',13);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',3,14,'dialogue_picture','A: 她是谁？ B: 她是我的老师。','','','["Багш","Эмч","Оюутан","Найз"]','Багш',14);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',3,15,'dialogue_picture','A: 你有几个孩子？ B: 我有一个女儿。','','','["Нэг охин","Хоёр хүү","Гурав","Тав"]','Нэг охин',15);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',4,16,'dialogue_answer','A: 你叫什么名字？ B: 我叫李明。 Q: 他叫什么？','','','["李明","王小","张三","赵四"]','李明',16);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',4,17,'dialogue_answer','A: 现在几点？ B: 现在五点半。 Q: 现在几点？','','','["5:30","3:30","7:30","9:30"]','5:30',17);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',4,18,'dialogue_answer','A: 你在哪儿工作？ B: 我在医院工作。 Q: 他在哪儿工作？','','','["Эмнэлэг","Сургууль","Дэлгүэр","Гэр"]','Эмнэлэг',18);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',4,19,'dialogue_answer','A: 明天天气怎么样？ B: 明天下雨。 Q: 明天天气好吗？','','','["Үгүй, бороотой","Тийм, сайн","Мэдэхгүй","Халуун"]','Үгүй, бороотой',19);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'listening',4,20,'dialogue_answer','A: 这个多少钱？ B: 十五块。 Q: 这个多少钱？','','','["15 юань","50 юань","5 юань","25 юань"]','15 юань',20);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',1,21,'word_picture','','苹果 píngguǒ','','["true","false"]','true',21);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',1,22,'word_picture','','电脑 diànnǎo = Телевиз','','["true","false"]','false',22);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',1,23,'word_picture','','医生 yīshēng = Эмч','','["true","false"]','true',23);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',1,24,'word_picture','','飞机 fēijī = Галт тэрэг','','["true","false"]','false',24);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',1,25,'word_picture','','学校 xuéxiào = Сургууль','','["true","false"]','true',25);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',2,26,'read_picture','','我喜欢吃米饭。Wǒ xǐhuan chī mǐfàn.','','["Будаа","Жимс","Цай","Алим"]','Будаа',26);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',2,27,'read_picture','','他在看电视。Tā zài kàn diànshì.','','["ТВ үзэж байна","Ном уншиж байна","Хоол хийж байна","Унтаж байна"]','ТВ үзэж байна',27);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',2,28,'read_picture','','今天很冷。Jīntiān hěn lěng.','','["Хүйтэн цаг агаар","Халуун цаг агаар","Бороо","Нартай"]','Хүйтэн цаг агаар',28);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',2,29,'read_picture','','她买了衣服。Tā mǎi le yīfu.','','["Хувцас","Ном","Жимс","Ус"]','Хувцас',29);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',2,30,'read_picture','','我坐出租车去。Wǒ zuò chūzūchē qù.','','["Такси","Онгоц","Галт тэрэг","Автобус"]','Такси',30);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',3,31,'sentence_match','','你叫什么名字？','','["我叫王小。","我很好。","我是学生。","我在家。"]','我叫王小。',31);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',3,32,'sentence_match','','你在哪儿工作？','','["我在医院工作。","我是中国人。","我喜欢看书。","我明天去。"]','我在医院工作。',32);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',3,33,'sentence_match','','今天星期几？','','["今天星期三。","今天很热。","今天下雨。","今天我去学校。"]','今天星期三。',33);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',3,34,'sentence_match','','你想喝什么？','','["我想喝茶。","我想去北京。","我想买衣服。","我想看电影。"]','我想喝茶。',34);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',3,35,'sentence_match','','你怎么去学校？','','["我坐出租车去。","我在学校。","我是学生。","我喜欢学校。"]','我坐出租车去。',35);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',4,36,'fill_blank','','我___喝茶。(like)','xǐhuan','["喜欢","想","在","会"]','喜欢',36);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',4,37,'fill_blank','','他是我的___。(friend)','péngyou','["朋友","老师","同学","医生"]','朋友',37);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',4,38,'fill_blank','','明天___怎么样？(weather)','tiānqì','["天气","时候","名字","东西"]','天气',38);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',4,39,'fill_blank','','我___一个苹果。(buy+了)','mǎi le','["买了","看了","吃了","喝了"]','买了',39);
INSERT INTO exam_questions (template_id,section,part_num,question_num,question_type,audio_text,question_text,question_pinyin,options,correct_answer,order_num) VALUES (1,'reading',4,40,'fill_blank','','现在___点？(how many)','jǐ','["几","什么","谁","哪"]','几',40);

-- Questions: 40