-- Migration: 0017_hsk1_examples_patch.sql
-- Idempotent: enrich example_zh/pinyin/mn for HSK1 words (safe re-run).

UPDATE words SET example_zh = '一二三四五。', example_pinyin = 'Yī èr sān sì wǔ.', example_mn = 'Neg hoyor guran duruw tavan.' WHERE id = 19 AND hsk_level = 1;
UPDATE words SET example_zh = '你是学生吗？', example_pinyin = 'Nǐ shì xuésheng ma?', example_mn = 'Chi oyutan uu?' WHERE id = 26 AND hsk_level = 1;
UPDATE words SET example_zh = '不客气！', example_pinyin = 'Bú kèqi!', example_mn = 'Zügeer!' WHERE id = 27 AND hsk_level = 1;
UPDATE words SET example_zh = '对不起，我来晚了。', example_pinyin = 'Duìbuqǐ, wǒ lái wǎn le.', example_mn = 'Uuchlaarai, bi hojuu irsen.' WHERE id = 28 AND hsk_level = 1;
UPDATE words SET example_zh = '没关系。', example_pinyin = 'Méi guānxi.', example_mn = 'Zügeer.' WHERE id = 29 AND hsk_level = 1;
UPDATE words SET example_zh = '请坐。', example_pinyin = 'Qǐng zuò.', example_mn = 'Suugaarai.' WHERE id = 30 AND hsk_level = 1;
UPDATE words SET example_zh = '同学们好。', example_pinyin = 'Tóngxué men hǎo.', example_mn = 'Angiin naizdaa sain uu?' WHERE id = 31 AND hsk_level = 1;
UPDATE words SET example_zh = '我也是学生。', example_pinyin = 'Wǒ yě shì xuésheng.', example_mn = 'Bi bas oyutan.' WHERE id = 32 AND hsk_level = 1;
UPDATE words SET example_zh = '我们去学校。', example_pinyin = 'Wǒmen qù xuéxiào.', example_mn = 'Bid surguulid ochloo.' WHERE id = 33 AND hsk_level = 1;
UPDATE words SET example_zh = '这是我的书。', example_pinyin = 'Zhè shì wǒ de shū.', example_mn = 'Ene minii nom.' WHERE id = 34 AND hsk_level = 1;
UPDATE words SET example_zh = '我叫李明。', example_pinyin = 'Wǒ jiào Lǐ Míng.', example_mn = 'Namaig Li Ming gedeg.' WHERE id = 35 AND hsk_level = 1;
UPDATE words SET example_zh = '你叫什么名字？', example_pinyin = 'Nǐ jiào shénme míngzi?', example_mn = 'Chinii ner yuu ve?' WHERE id = 36 AND hsk_level = 1;
UPDATE words SET example_zh = '他的名字很好。', example_pinyin = 'Tā de míngzi hěn hǎo.', example_mn = 'Tuunii ner sain.' WHERE id = 37 AND hsk_level = 1;
UPDATE words SET example_zh = '很高兴认识你。', example_pinyin = 'Hěn gāoxìng rènshi nǐ.', example_mn = 'Chamtai taniltsand bayartai.' WHERE id = 38 AND hsk_level = 1;
UPDATE words SET example_zh = '我很高兴。', example_pinyin = 'Wǒ hěn gāoxìng.', example_mn = 'Bi mash bayartai.' WHERE id = 39 AND hsk_level = 1;
UPDATE words SET example_zh = '你是哪国人？', example_pinyin = 'Nǐ shì nǎ guó rén?', example_mn = 'Chi als ulsyn hün be?' WHERE id = 40 AND hsk_level = 1;
UPDATE words SET example_zh = '中国很大。', example_pinyin = 'Zhōngguó hěn dà.', example_mn = 'Hyatad uls tom.' WHERE id = 41 AND hsk_level = 1;
UPDATE words SET example_zh = '天气很冷。', example_pinyin = 'Tiānqì hěn lěng.', example_mn = 'Tsag agaar mash hüiten.' WHERE id = 42 AND hsk_level = 1;
UPDATE words SET example_zh = '这是我的妈妈。', example_pinyin = 'Zhè shì wǒ de māma.', example_mn = 'Ene minii eej.' WHERE id = 43 AND hsk_level = 1;
UPDATE words SET example_zh = '那是我爸爸。', example_pinyin = 'Nà shì wǒ de bàba.', example_mn = 'Ter minii aav.' WHERE id = 44 AND hsk_level = 1;
UPDATE words SET example_zh = '他是谁？', example_pinyin = 'Tā shì shéi?', example_mn = 'Ter hen be?' WHERE id = 45 AND hsk_level = 1;
UPDATE words SET example_zh = '我爸爸很忙。', example_pinyin = 'Wǒ bàba hěn máng.', example_mn = 'Minii aav mash zavgui.' WHERE id = 46 AND hsk_level = 1;
UPDATE words SET example_zh = '妈妈在家。', example_pinyin = 'Māma zài jiā.', example_mn = 'Eej gereetee.' WHERE id = 47 AND hsk_level = 1;
UPDATE words SET example_zh = '我有一个女儿。', example_pinyin = 'Wǒ yǒu yí ge nǚ''ér.', example_mn = 'Nadad neg ohin baina.' WHERE id = 48 AND hsk_level = 1;
UPDATE words SET example_zh = '他儿子七岁。', example_pinyin = 'Tā érzi qī suì.', example_mn = 'Tuunii hüü doloon nastai.' WHERE id = 49 AND hsk_level = 1;
UPDATE words SET example_zh = '王先生很好。', example_pinyin = 'Wáng xiānsheng hěn hǎo.', example_mn = 'Aga Wang mash sain.' WHERE id = 50 AND hsk_level = 1;
UPDATE words SET example_zh = '李小姐在北京。', example_pinyin = 'Lǐ xiǎojiě zài Běijīng.', example_mn = 'Li hatagtai Beejingd.' WHERE id = 51 AND hsk_level = 1;
UPDATE words SET example_zh = '他是我的朋友。', example_pinyin = 'Tā shì wǒ de péngyou.', example_mn = 'Ter minii naiz.' WHERE id = 52 AND hsk_level = 1;
UPDATE words SET example_zh = '妈妈是医生。', example_pinyin = 'Māma shì yīshēng.', example_mn = 'Eej emch.' WHERE id = 53 AND hsk_level = 1;
UPDATE words SET example_zh = '你去哪儿？', example_pinyin = 'Nǐ qù nǎr?', example_mn = 'Chi haasha yavah ve?' WHERE id = 54 AND hsk_level = 1;
UPDATE words SET example_zh = '我在学校学习。', example_pinyin = 'Wǒ zài xuéxiào xuéxí.', example_mn = 'Bi surguulid suraltsana.' WHERE id = 55 AND hsk_level = 1;
UPDATE words SET example_zh = '我会说汉语。', example_pinyin = 'Wǒ huì shuō Hànyǔ.', example_mn = 'Bi hyatadaar yarij chaddag.' WHERE id = 56 AND hsk_level = 1;
UPDATE words SET example_zh = '今年我二十岁。', example_pinyin = 'Jīnnián wǒ èrshí suì.', example_mn = 'Ene jil bi hoyor nastai.' WHERE id = 57 AND hsk_level = 1;
UPDATE words SET example_zh = '现在几点？', example_pinyin = 'Xiànzài jǐ diǎn?', example_mn = 'Odoo hed tsag ve?' WHERE id = 58 AND hsk_level = 1;
UPDATE words SET example_zh = '你几岁？', example_pinyin = 'Nǐ jǐ suì?', example_mn = 'Chi hed nastai ve?' WHERE id = 59 AND hsk_level = 1;
UPDATE words SET example_zh = '你多大？', example_pinyin = 'Nǐ duō dà?', example_mn = 'Chi hed nastai ve?' WHERE id = 60 AND hsk_level = 1;
UPDATE words SET example_zh = '我想喝茶。', example_pinyin = 'Wǒ xiǎng hē chá.', example_mn = 'Bi tsai uumaar baina.' WHERE id = 85 AND hsk_level = 1;
UPDATE words SET example_zh = '一杯水。', example_pinyin = 'Yì bēi shuǐ.', example_mn = 'Neg ayaga us.' WHERE id = 87 AND hsk_level = 1;
UPDATE words SET example_zh = '我喜欢米饭。', example_pinyin = 'Wǒ xǐhuan mǐfàn.', example_mn = 'Bi budatai hool dortoi.' WHERE id = 89 AND hsk_level = 1;
UPDATE words SET example_zh = '我在家。', example_pinyin = 'Wǒ zài jiā.', example_mn = 'Bi gereetei.' WHERE id = 93 AND hsk_level = 1;
UPDATE words SET example_zh = '他在医院工作。', example_pinyin = 'Tā zài yīyuàn gōngzuò.', example_mn = 'Ter emnellegt ajillana.' WHERE id = 94 AND hsk_level = 1;
UPDATE words SET example_zh = '请坐。', example_pinyin = 'Qǐng zuò.', example_mn = 'Suugaarai.' WHERE id = 102 AND hsk_level = 1;
UPDATE words SET example_zh = '我在这儿。', example_pinyin = 'Wǒ zài zhèr.', example_mn = 'Bi end baina.' WHERE id = 103 AND hsk_level = 1;
UPDATE words SET example_zh = '现在八点半。', example_pinyin = 'Xiànzài bā diǎn bàn.', example_mn = 'Odoo naim gantshan.' WHERE id = 110 AND hsk_level = 1;
UPDATE words SET example_zh = '今天天气怎么样？', example_pinyin = 'Jīntiān tiānqì zěnmeyàng?', example_mn = 'Önöödör tsag agaar yaamar baina?' WHERE id = 120 AND hsk_level = 1;
UPDATE words SET example_zh = '他喜欢学习。', example_pinyin = 'Tā xǐhuan xuéxí.', example_mn = 'Ter suraltsmagd dostoi.' WHERE id = 128 AND hsk_level = 1;
UPDATE words SET example_zh = '你呢？', example_pinyin = 'Nǐ ne?', example_mn = 'Chi yaamar baina?' WHERE id = 129 AND hsk_level = 1;
UPDATE words SET example_zh = '我喜欢看电视。', example_pinyin = 'Wǒ xǐhuan kàn diànshì.', example_mn = 'Bi televis üzehd dortoi.' WHERE id = 130 AND hsk_level = 1;
UPDATE words SET example_zh = '我买了一个苹果。', example_pinyin = 'Wǒ mǎi le yí ge píngguǒ.', example_mn = 'Bi neg alim awsan.' WHERE id = 136 AND hsk_level = 1;
UPDATE words SET example_zh = '他来了。', example_pinyin = 'Tā lái le.', example_mn = 'Ter irsen.' WHERE id = 137 AND hsk_level = 1;
UPDATE words SET example_zh = '我没有钱。', example_pinyin = 'Wǒ méiyǒu qián.', example_mn = 'Nadad mönög baihgüi.' WHERE id = 139 AND hsk_level = 1;
UPDATE words SET example_zh = '我坐飞机去北京。', example_pinyin = 'Wǒ zuò fēijī qù Běijīng.', example_mn = 'Bi ongotsoor Beejing yavna.' WHERE id = 144 AND hsk_level = 1;
UPDATE words SET example_zh = '你怎么去学校？', example_pinyin = 'Nǐ zěnme qù xuéxiào?', example_mn = 'Chi yaaj surguuld ochdog ve?' WHERE id = 150 AND hsk_level = 1;
UPDATE words SET example_zh = '我们都在家。', example_pinyin = 'Wǒmen dōu zài jiā.', example_mn = 'Bid bugd gereetei.' WHERE id = 151 AND hsk_level = 1;
UPDATE words SET example_zh = '他没去北京。', example_pinyin = 'Tā méi qù Běijīng.', example_mn = 'Ter Beejing yavsangui.' WHERE id = 152 AND hsk_level = 1;
UPDATE words SET example_zh = '我没有时间。', example_pinyin = 'Wǒ méiyǒu shíjiān.', example_mn = 'Nadad tsag baihgüi.' WHERE id = 153 AND hsk_level = 1;
UPDATE words SET example_zh = '我有一本书。', example_pinyin = 'Wǒ yǒu yì běn shū.', example_mn = 'Nadad neg nom baina.' WHERE id = 154 AND hsk_level = 1;
UPDATE words SET example_zh = '我要睡觉。', example_pinyin = 'Wǒ yào shuìjiào.', example_mn = 'Bi unthmaar baina.' WHERE id = 155 AND hsk_level = 1;