import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '../../theme';

export const mockExamStyles = StyleSheet.create({
  h1: { ...typography.heading.lg, marginBottom: spacing.sm },
  p: { ...typography.body.md, color: colors.text.secondary, marginBottom: spacing.xs },
  muted: { ...typography.body.md, color: colors.text.muted },
  meta: { ...typography.body.sm, color: colors.text.secondary, marginBottom: spacing.sm },
  runHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  runMeta: { ...typography.body.sm, color: colors.text.secondary },
  quitLink: { ...typography.body.md, fontWeight: '600' as const, color: colors.text.secondary },
  pickerBack: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    alignSelf: 'flex-start',
    marginBottom: spacing.md,
    paddingVertical: spacing.xs,
  },
  pickerBackTx: { ...typography.body.md, color: colors.brand.primary },
  doneExit: {
    marginTop: spacing.lg,
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  doneExitTx: { ...typography.body.md, color: colors.text.primary },
  prompt: { ...typography.body.md, color: colors.text.primary, marginBottom: spacing.lg },
  opts: { gap: spacing.sm },
  opt: {
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg.card,
  },
  optOn: { borderColor: colors.brand.primary },
  optTx: { ...typography.body.md },
  nav: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.lg },
  navBtn: { padding: spacing.md },
  navTx: { fontSize: 24, color: colors.brand.primary },
  submit: {
    marginTop: spacing.lg,
    backgroundColor: colors.brand.primary,
    padding: spacing.md,
    borderRadius: radius.lg,
    alignItems: 'center',
  },
  submitTx: { color: '#fff', ...typography.heading.sm },
  pickerWrap: { gap: spacing.sm },
  tplRow: {
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg.card,
    marginBottom: spacing.sm,
  },
  tplTitle: { ...typography.body.md, fontWeight: '700' as const, color: colors.text.primary },
  tplMeta: { ...typography.body.sm, color: colors.text.muted, marginTop: 4 },
});
