import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../theme';

export const lessonEditorStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: colors.bg.primary },
  hdr: { padding: spacing.md, gap: spacing.xs },
  lbl: { ...typography.body.sm, color: colors.text.secondary },
  inp: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: spacing.sm,
    color: colors.text.primary,
    backgroundColor: colors.bg.card,
  },
  rowTap: { paddingVertical: spacing.sm },
  primary: {
    padding: spacing.md,
    backgroundColor: colors.brand.primary,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  primaryTxt: { color: '#fff', fontWeight: '700' },
  secondary: {
    padding: spacing.md,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.brand.secondary,
    alignItems: 'center',
    marginTop: spacing.sm,
    backgroundColor: colors.bg.card,
  },
  secondaryTxt: { color: colors.brand.secondary, fontWeight: '700' },
  danger: {
    padding: spacing.md,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.error,
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  dangerTxt: { color: colors.error, fontWeight: '700' },
  row: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center' },
  flex1: { flex: 1 },
  wrow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  hz: { ...typography.heading.sm, color: colors.text.primary },
  meta: { ...typography.body.sm, color: colors.text.secondary },
  rm: { color: colors.error, fontWeight: '700' },
  wordOrderBtns: { flexDirection: 'column', gap: 4, marginRight: spacing.sm },
  ordBtn: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg.card,
  },
  ordBtnDis: { opacity: 0.35 },
  ordTxt: { ...typography.body.sm, color: colors.text.primary, fontWeight: '700' },
  center: { flex: 1, justifyContent: 'center', padding: spacing.lg },
  muted: { ...typography.body.md, color: colors.text.muted, textAlign: 'center' },
});
