import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../theme';

export const adminExamPdfImportStyles = StyleSheet.create({
  wrap: {
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
    backgroundColor: colors.bg.secondary,
    gap: spacing.sm,
  },
  center: { flex: 1, justifyContent: 'center', padding: spacing.lg },
  muted: { ...typography.body.md, color: colors.text.muted, textAlign: 'center' },
  warn: { ...typography.body.sm, color: colors.warning, lineHeight: 18 },
  label: { ...typography.body.sm, fontWeight: '600', color: colors.text.secondary },
  inp: {
    ...typography.body.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: spacing.sm,
    backgroundColor: colors.bg.primary,
    color: colors.text.primary,
  },
  inpSm: {
    ...typography.body.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: spacing.sm,
    backgroundColor: colors.bg.primary,
    color: colors.text.primary,
  },
  row: { flexDirection: 'row', gap: spacing.md },
  cell: { flex: 1, gap: 4 },
  pubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.xs,
  },
  pubHint: { ...typography.body.sm, color: colors.text.muted, lineHeight: 18 },
  pick: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.sm,
    borderRadius: 8,
    backgroundColor: colors.bg.primary,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.sm,
  },
  pickL: { ...typography.body.sm, color: colors.text.secondary, flexShrink: 0 },
  pickV: { ...typography.body.sm, color: colors.text.primary, flex: 1, textAlign: 'right' },
  btns: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.xs },
  btn: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 8,
    backgroundColor: colors.bg.primary,
    borderWidth: 1,
    borderColor: colors.border,
  },
  btnPri: { backgroundColor: colors.brand.primary, borderColor: colors.brand.primary },
  btnTx: { ...typography.body.md, color: colors.text.primary, fontWeight: '600' },
  btnTxPri: { color: '#fff' },
  spin: { marginVertical: spacing.sm },
  err: { ...typography.body.sm, color: colors.error },
  draftBox: { marginTop: spacing.md, gap: spacing.xs },
  draftTit: { ...typography.body.sm, fontWeight: '700', color: colors.text.primary },
  draftLn: { ...typography.body.sm, color: colors.text.secondary, lineHeight: 18 },
  draftKey: { ...typography.body.sm, color: colors.text.muted },
  more: { ...typography.body.sm, color: colors.text.muted },
});
