import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../theme';

export const bulkHanziStyles = StyleSheet.create({
  block: { marginTop: spacing.xl, paddingTop: spacing.lg, borderTopWidth: 1, borderTopColor: colors.border },
  sectionTitle: { ...typography.heading.sm, color: colors.text.primary, marginBottom: spacing.xs },
  hintTiny: { ...typography.body.sm, color: colors.text.muted, marginBottom: spacing.sm },
  textarea: {
    minHeight: 140,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: spacing.sm,
    color: colors.text.primary,
    backgroundColor: colors.bg.card,
    marginBottom: spacing.sm,
  },
  btnSec: {
    alignSelf: 'flex-start',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.md,
    backgroundColor: colors.bg.secondary,
  },
  btnSecTx: { ...typography.body.md, fontWeight: '600', color: colors.text.primary },
  previewBox: { marginBottom: spacing.md },
  previewMeta: { ...typography.body.sm, fontWeight: '700', marginBottom: spacing.xs },
  errLine: { ...typography.body.sm, color: colors.error, marginBottom: 2 },
  okLine: { ...typography.body.sm, color: colors.text.secondary, marginBottom: 2 },
  okMean: { ...typography.body.sm, color: colors.text.primary, marginBottom: 6 },
  okSharedEx: { ...typography.body.sm, color: colors.text.muted, marginTop: spacing.xs },
  errMore: { ...typography.body.sm, color: colors.text.muted },
  btn: {
    padding: spacing.md,
    backgroundColor: colors.brand.primary,
    borderRadius: 12,
    alignItems: 'center',
  },
  btnDis: { opacity: 0.5 },
  btnPressed: { opacity: 0.92 },
  btnWeb: { cursor: 'pointer' as const },
  btnTxt: { ...typography.body.md, color: '#fff', fontWeight: '700' },
  toolsBlock: { marginBottom: spacing.md, gap: spacing.xs },
  toolsLabel: { ...typography.body.sm, color: colors.text.secondary, marginTop: spacing.xs },
  toolsInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: spacing.sm,
    color: colors.text.primary,
    backgroundColor: colors.bg.card,
  },
  segRow: { flexDirection: 'row', gap: spacing.sm, flexWrap: 'wrap' },
  segBtn: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg.secondary,
  },
  segBtnOn: { borderColor: colors.brand.primary, backgroundColor: colors.bg.card },
  segTx: { ...typography.body.sm, fontWeight: '600', color: colors.text.primary },
});
