import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../theme';

export const cartoonAttachStyles = StyleSheet.create({
  back: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  sheet: {
    maxHeight: '88%',
    backgroundColor: colors.bg.primary,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: spacing.md,
  },
  title: { ...typography.heading.md, color: colors.text.primary, marginBottom: spacing.sm },
  row: { flexDirection: 'row', gap: spacing.xs, alignItems: 'center', marginBottom: spacing.sm },
  inp: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: spacing.sm,
    color: colors.text.primary,
    backgroundColor: colors.bg.card,
  },
  wid: { width: 72 },
  num: { width: 56 },
  pick: { padding: spacing.sm, backgroundColor: colors.accent.teal, borderRadius: 8 },
  pickTxt: { color: '#fff', fontWeight: '700', fontSize: 12 },
  searchBox: { marginBottom: spacing.sm },
  searchRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.xs },
  inpFlex: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: spacing.sm,
    color: colors.text.primary,
  },
  go: {
    paddingHorizontal: spacing.md,
    justifyContent: 'center',
    backgroundColor: colors.brand.primary,
    borderRadius: 8,
  },
  goTxt: { color: '#fff', fontWeight: '700' },
  hit: { paddingVertical: spacing.xs, borderBottomWidth: 1, borderBottomColor: colors.border },
  hitTxt: { ...typography.body.sm, color: colors.text.primary },
  addRow: { alignSelf: 'flex-start', padding: spacing.sm },
  addRowTxt: { color: colors.brand.primary, fontWeight: '700' },
  footer: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md },
  secondary: {
    flex: 1,
    padding: spacing.md,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  secondaryTxt: { fontWeight: '600', color: colors.text.primary },
  primary: {
    flex: 1,
    padding: spacing.md,
    borderRadius: 12,
    backgroundColor: colors.brand.primary,
    alignItems: 'center',
  },
  primaryTxt: { color: '#fff', fontWeight: '700' },
});
