# ruff: noqa: E501
"""Question bank for HSK 1 mock exams. Scoring: listening max 100 + reading max 100 = 200 (see examScoring.ts)."""

# Each: (section, part, qtype, audio_text, question_text, pinyin, options_json, correct)
EXAM1 = [
  ('listening',1,'picture_match','我喜欢喝茶。','Цай уух дуртай хүн','','["true","false"]','true'),
  ('listening',1,'picture_match','他在看书。','Хоол хийж байгаа хүн','','["true","false"]','false'),
  ('listening',1,'picture_match','今天下雨了。','Бороо орж байна','','["true","false"]','true'),
  ('listening',1,'picture_match','她是医生。','Багш','','["true","false"]','false'),
  ('listening',1,'picture_match','我有一只猫。','Муур','','["true","false"]','true'),
  ('listening',2,'sentence_picture','我想吃苹果。','','','["Алим","Ном","Ус","Цай"]','Алим'),
  ('listening',2,'sentence_picture','他坐飞机去北京。','','','["Онгоц","Галт тэрэг","Такси","Машин"]','Онгоц'),
  ('listening',2,'sentence_picture','现在三点了。','','','["3:00","5:00","7:00","9:00"]','3:00'),
  ('listening',2,'sentence_picture','她在学校学习。','','','["Сургууль","Эмнэлэг","Дэлгүүр","Гэр"]','Сургууль'),
  ('listening',2,'sentence_picture','我买了一些水果。','','','["Жимс","Хувцас","Ном","Ус"]','Жимс'),
  ('listening',3,'dialogue_picture','A: 你想喝什么？ B: 我想喝茶。','','','["Цай","Ус","Кофе","Сүү"]','Цай'),
  ('listening',3,'dialogue_picture','A: 今天天气怎么样？ B: 今天很热。','','','["Халуун нар","Бороо","Цас","Хүйтэн"]','Халуун нар'),
  ('listening',3,'dialogue_picture','A: 你去哪儿？ B: 我去医院。','','','["Эмнэлэг","Сургууль","Дэлгүэр","Гэр"]','Эмнэлэг'),
  ('listening',3,'dialogue_picture','A: 她是谁？ B: 她是我的老师。','','','["Багш","Эмч","Оюутан","Найз"]','Багш'),
  ('listening',3,'dialogue_picture','A: 你有几个孩子？ B: 我有一个女儿。','','','["Нэг охин","Хоёр хүү","Гурав","Тав"]','Нэг охин'),
  ('listening',4,'dialogue_answer','A: 你叫什么名字？ B: 我叫李明。 Q: 他叫什么？','','','["李明","王小","张三","赵四"]','李明'),
  ('listening',4,'dialogue_answer','A: 现在几点？ B: 现在五点半。 Q: 现在几点？','','','["5:30","3:30","7:30","9:30"]','5:30'),
  ('listening',4,'dialogue_answer','A: 你在哪儿工作？ B: 我在医院工作。 Q: 他在哪儿工作？','','','["Эмнэлэг","Сургууль","Дэлгүэр","Гэр"]','Эмнэлэг'),
  ('listening',4,'dialogue_answer','A: 明天天气怎么样？ B: 明天下雨。 Q: 明天天气好吗？','','','["Үгүй, бороотой","Тийм, сайн","Мэдэхгүй","Халуун"]','Үгүй, бороотой'),
  ('listening',4,'dialogue_answer','A: 这个多少钱？ B: 十五块。 Q: 这个多少钱？','','','["15 юань","50 юань","5 юань","25 юань"]','15 юань'),
  ('reading',1,'word_picture','','苹果 píngguǒ','','["true","false"]','true'),
  ('reading',1,'word_picture','','电脑 diànnǎo = Телевиз','','["true","false"]','false'),
  ('reading',1,'word_picture','','医生 yīshēng = Эмч','','["true","false"]','true'),
  ('reading',1,'word_picture','','飞机 fēijī = Галт тэрэг','','["true","false"]','false'),
  ('reading',1,'word_picture','','学校 xuéxiào = Сургууль','','["true","false"]','true'),
  ('reading',2,'read_picture','','我喜欢吃米饭。Wǒ xǐhuan chī mǐfàn.','','["Будаа","Жимс","Цай","Алим"]','Будаа'),
  ('reading',2,'read_picture','','他在看电视。Tā zài kàn diànshì.','','["ТВ үзэж байна","Ном уншиж байна","Хоол хийж байна","Унтаж байна"]','ТВ үзэж байна'),
  ('reading',2,'read_picture','','今天很冷。Jīntiān hěn lěng.','','["Хүйтэн цаг агаар","Халуун цаг агаар","Бороо","Нартай"]','Хүйтэн цаг агаар'),
  ('reading',2,'read_picture','','她买了衣服。Tā mǎi le yīfu.','','["Хувцас","Ном","Жимс","Ус"]','Хувцас'),
  ('reading',2,'read_picture','','我坐出租车去。Wǒ zuò chūzūchē qù.','','["Такси","Онгоц","Галт тэрэг","Автобус"]','Такси'),
  ('reading',3,'sentence_match','','你叫什么名字？','','["我叫王小。","我很好。","我是学生。","我在家。"]','我叫王小。'),
  ('reading',3,'sentence_match','','你在哪儿工作？','','["我在医院工作。","我是中国人。","我喜欢看书。","我明天去。"]','我在医院工作。'),
  ('reading',3,'sentence_match','','今天星期几？','','["今天星期三。","今天很热。","今天下雨。","今天我去学校。"]','今天星期三。'),
  ('reading',3,'sentence_match','','你想喝什么？','','["我想喝茶。","我想去北京。","我想买衣服。","我想看电影。"]','我想喝茶。'),
  ('reading',3,'sentence_match','','你怎么去学校？','','["我坐出租车去。","我在学校。","我是学生。","我喜欢学校。"]','我坐出租车去。'),
  ('reading',4,'fill_blank','','我___喝茶。(like)','xǐhuan','["喜欢","想","在","会"]','喜欢'),
  ('reading',4,'fill_blank','','他是我的___。(friend)','péngyou','["朋友","老师","同学","医生"]','朋友'),
  ('reading',4,'fill_blank','','明天___怎么样？(weather)','tiānqì','["天气","时候","名字","东西"]','天气'),
  ('reading',4,'fill_blank','','我___一个苹果。(buy+了)','mǎi le','["买了","看了","吃了","喝了"]','买了'),
  ('reading',4,'fill_blank','','现在___点？(how many)','jǐ','["几","什么","谁","哪"]','几'),
]
