# ruff: noqa: E501
"""HSK1 generator data: vocabulary, lessons, optional example sentences."""

from typing import Dict, Optional, Tuple

EXISTING = {
    "你好": 1,
    "谢谢": 2,
    "再见": 3,
    "我": 4,
    "你": 5,
    "他": 6,
    "她": 7,
    "是": 8,
    "不": 9,
    "好": 10,
    "大": 11,
    "小": 12,
    "人": 13,
    "中国": 14,
    "学生": 15,
    "老师": 16,
    "一": 17,
    "二": 18,
    "三": 19,
    "吃": 20,
    "喝": 21,
    "来": 22,
    "去": 23,
    "看": 24,
    "说": 25,
}

NEW_WORDS = [
    ("吗", "ma", "~uu/~үү (asuuh)", "(question particle)", "particle"),
    ("不客气", "bú kèqi", "Zügeer", "You're welcome", "phrase"),
    ("对不起", "duìbuqǐ", "Uuchlaarai", "Sorry", "phrase"),
    ("没关系", "méi guānxi", "Zügeer dee", "It doesn't matter", "phrase"),
    ("请", "qǐng", "Guiya", "Please", "verb"),
    ("同学", "tóngxué", "Angiin naiz", "Classmate", "noun"),
    ("也", "yě", "Bas/mön", "Also", "adverb"),
    ("们", "men", "~nar (olon too)", "(plural suffix)", "particle"),
    ("的", "de", "~iin/~iin", "(possessive particle)", "particle"),
    ("叫", "jiào", "Nerledeg", "To be called", "verb"),
    ("什么", "shénme", "Yuu", "What", "pronoun"),
    ("名字", "míngzi", "Ner", "Name", "noun"),
    ("认识", "rènshi", "Taniltsah", "To know/recognize", "verb"),
    ("高兴", "gāoxìng", "Bayartai", "Happy", "adjective"),
    ("哪", "nǎ", "Ali", "Which", "pronoun"),
    ("国", "guó", "Uls", "Country", "noun"),
    ("很", "hěn", "Mash", "Very", "adverb"),
    ("这", "zhè", "Ene", "This", "pronoun"),
    ("那", "nà", "Ter", "That", "pronoun"),
    ("谁", "shéi", "Hen", "Who", "pronoun"),
    ("爸爸", "bàba", "Aav", "Father", "noun"),
    ("妈妈", "māma", "Eej", "Mother", "noun"),
    ("女儿", "nǚ'ér", "Ohin", "Daughter", "noun"),
    ("儿子", "érzi", "Hüü", "Son", "noun"),
    ("先生", "xiānsheng", "Noön", "Mr./Sir", "noun"),
    ("小姐", "xiǎojiě", "Hatagtai", "Miss", "noun"),
    ("朋友", "péngyou", "Naiz", "Friend", "noun"),
    ("医生", "yīshēng", "Emch", "Doctor", "noun"),
    ("哪儿", "nǎr", "Haana", "Where", "pronoun"),
    ("学校", "xuéxiào", "Surguuli", "School", "noun"),
    ("汉语", "Hànyǔ", "Hyatad hel", "Chinese language", "noun"),
    ("今年", "jīnnián", "Ene jil", "This year", "noun"),
    ("几", "jǐ", "Hed", "How many/which", "pronoun"),
    ("岁", "suì", "Nas", "Years old", "noun"),
    ("多大", "duō dà", "Hedeen nastai", "How old", "phrase"),
    ("四", "sì", "Döröw", "Four", "number"),
    ("五", "wǔ", "Taw", "Five", "number"),
    ("六", "liù", "Zurgaa", "Six", "number"),
    ("七", "qī", "Doloo", "Seven", "number"),
    ("八", "bā", "Naim", "Eight", "number"),
    ("九", "jiǔ", "Yos", "Nine", "number"),
    ("十", "shí", "Araw", "Ten", "number"),
    ("零", "líng", "Teg", "Zero", "number"),
    ("会", "huì", "Chaddag", "Can/able to", "verb"),
    ("读", "dú", "Unshih", "To read", "verb"),
    ("写", "xiě", "Bichih", "To write", "verb"),
    ("听", "tīng", "Sonsooh", "To listen", "verb"),
    ("能", "néng", "Chadah", "Can/able", "verb"),
    ("一点儿", "yìdiǎnr", "Jaahan", "A little", "phrase"),
    ("字", "zì", "Üseg/Temdeg", "Character", "noun"),
    ("和", "hé", "Ba/bolon", "And", "conjunction"),
    ("今天", "jīntiān", "Önöödör", "Today", "noun"),
    ("号", "hào", "Saryn ödör", "Date/number", "noun"),
    ("月", "yuè", "Sar", "Month", "noun"),
    ("星期", "xīngqī", "Doloo honog", "Week", "noun"),
    ("明天", "míngtiān", "Маргааш", "Tomorrow", "noun"),
    ("昨天", "zuótiān", "Öchigdör", "Yesterday", "noun"),
    ("年", "nián", "Jil", "Year", "noun"),
    ("日", "rì", "Ödör", "Day/date", "noun"),
    ("想", "xiǎng", "~maar baina", "Want/think", "verb"),
    ("茶", "chá", "Tsai", "Tea", "noun"),
    ("杯子", "bēizi", "Ayaga", "Cup/glass", "noun"),
    ("水", "shuǐ", "Us", "Water", "noun"),
    ("米饭", "mǐfàn", "Budaatai hool", "Rice", "noun"),
    ("菜", "cài", "Hool/Nogoo", "Dish/vegetable", "noun"),
    ("苹果", "píngguǒ", "Alim", "Apple", "noun"),
    ("水果", "shuǐguǒ", "Jims", "Fruit", "noun"),
    ("在", "zài", "~d baina", "At/in", "preposition"),
    ("工作", "gōngzuò", "Ajil/Ajillah", "Work", "verb"),
    ("医院", "yīyuàn", "Emnelleg", "Hospital", "noun"),
    ("商店", "shāngdiàn", "Delgüür", "Shop/store", "noun"),
    ("后面", "hòumian", "Ard/Hoino", "Behind", "noun"),
    ("前面", "qiánmian", "Ömnö", "In front", "noun"),
    ("里面", "lǐmian", "Dotor", "Inside", "noun"),
    ("上", "shàng", "Deer", "Up/on", "noun"),
    ("下", "xià", "Door", "Down/under", "noun"),
    ("坐", "zuò", "Suuh", "To sit", "verb"),
    ("这儿", "zhèr", "End", "Here", "pronoun"),
    ("那儿", "nàr", "Tend", "There", "pronoun"),
    ("桌子", "zhuōzi", "Shiree", "Table/desk", "noun"),
    ("椅子", "yǐzi", "Sandal", "Chair", "noun"),
    ("书", "shū", "Nom", "Book", "noun"),
    ("些", "xiē", "Zarim neg", "Some", "pronoun"),
    ("本", "běn", "(nom tooloh)", "(measure word for books)", "measure_word"),
    ("现在", "xiànzài", "Odoo", "Now", "noun"),
    ("点", "diǎn", "Tseg/Tsag", "O'clock/dot", "noun"),
    ("分钟", "fēnzhōng", "Minut", "Minute", "noun"),
    ("时候", "shíhou", "Üe/Tsag", "Time/moment", "noun"),
    ("上午", "shàngwǔ", "Öglöö", "Morning/AM", "noun"),
    ("下午", "xiàwǔ", "Ödriin hoid", "Afternoon/PM", "noun"),
    ("中午", "zhōngwǔ", "Üd dund", "Noon", "noun"),
    ("回", "huí", "Butsah", "To return", "verb"),
    ("做", "zuò", "Hiih", "To do/make", "verb"),
    ("打电话", "dǎ diànhuà", "Utsaar yarih", "Make a phone call", "phrase"),
    ("天气", "tiānqì", "Tsag agaar", "Weather", "noun"),
    ("怎么样", "zěnmeyàng", "Yaaj/Yamar", "How about/How", "pronoun"),
    ("太", "tài", "Hetherhii", "Too (much)", "adverb"),
    ("热", "rè", "Haluun", "Hot", "adjective"),
    ("冷", "lěng", "Hüiten", "Cold", "adjective"),
    ("下雨", "xià yǔ", "Boroo oroh", "To rain", "verb"),
    ("多", "duō", "olon/Ih", "Many/much", "adjective"),
    ("少", "shǎo", "Tsöön/Baga", "Few/little", "adjective"),
    ("学习", "xuéxí", "Suraltsah", "To study", "verb"),
    ("呢", "ne", "~yuu? (asuuh)", "(question particle)", "particle"),
    ("喜欢", "xǐhuan", "Durtai", "To like", "verb"),
    ("爱", "ài", "Hairlah", "To love", "verb"),
    ("电影", "diànyǐng", "Kino", "Movie", "noun"),
    ("电视", "diànshì", "Televiz", "Television", "noun"),
    ("电脑", "diànnǎo", "Kompyuter", "Computer", "noun"),
    ("东西", "dōngxi", "Yum/Züjl", "Thing/stuff", "noun"),
    ("买", "mǎi", "Hudaldaj awah", "To buy", "verb"),
    ("了", "le", "(duussan)", "(completed action particle)", "particle"),
    ("衣服", "yīfu", "Huwtsas", "Clothes", "noun"),
    ("钱", "qián", "Mönög", "Money", "noun"),
    ("块", "kuài", "Tögrög/yuan", "Yuan/piece", "measure_word"),
    ("多少", "duōshao", "Hed/Hedeen", "How many/much", "pronoun"),
    ("个", "gè", "(tooloh üg)", "(general measure word)", "measure_word"),
    ("漂亮", "piàoliang", "Üzesgelengtei", "Beautiful", "adjective"),
    ("飞机", "fēijī", "Ongots", "Airplane", "noun"),
    ("出租车", "chūzūchē", "Taksi", "Taxi", "noun"),
    ("火车", "huǒchē", "Galt tereg", "Train", "noun"),
    ("住", "zhù", "Ajildrah/Bairlah", "To live", "verb"),
    ("家", "jiā", "Ger", "Home/family", "noun"),
    ("北京", "Běijīng", "Beejing", "Beijing", "noun"),
    ("怎么", "zěnme", "Yaaj/Yagaad", "How/why", "pronoun"),
    ("都", "dōu", "Bugd", "All/both", "adverb"),
    ("没", "méi", "Ügüi (öngrösun)", "Not (past)", "adverb"),
    ("没有", "méiyǒu", "Baihgüi", "Don't have", "verb"),
    ("有", "yǒu", "Baina/Bii", "To have", "verb"),
    ("睡觉", "shuìjiào", "Untah", "To sleep", "verb"),
]

# (zh_unit_anchor, title_mn, subtitle_mn, icon, words) — subtitle: HSK 1 сурах бичгийн нэгж + товч гол сэдэв
LESSONS = [
    ("你好", "Мэндчилгээ", "Нэгж 1 · Мэндчилгээ (你好)", "hand-right", ["你好", "我", "你", "他", "她", "是", "不", "好", "吗", "老师"]),
    ("谢谢你", "Талархал", "Нэгж 2 · Талархал ба уучлал (谢谢)", "heart", ["谢谢", "再见", "不客气", "对不起", "没关系", "请", "同学", "也", "们", "的"]),
    ("你叫什么名字？", "Нэр хэлэх", "Нэгж 3 · Тоотой асуулт ба нэр (名字)", "people", ["叫", "什么", "名字", "认识", "高兴", "哪", "国", "人", "中国", "很"]),
    ("她是我的汉语老师", "Танилцуулга", "Нэгж 4 · Гэр бүл, мэргэжил (朋友)", "school", ["学生", "这", "那", "谁", "爸爸", "妈妈", "朋友", "医生", "哪儿", "学校"]),
    ("她女儿今年二十岁", "Нас, гэр бүл", "Нэгж 5 · Олон тоо, нас (岁)", "calendar", ["汉语", "今年", "几", "岁", "多大", "女儿", "儿子", "先生", "小姐", "四"]),
    ("我会说汉语", "Чадвар", "Нэгж 6 · Чадвар илэрхийлэх (会)", "chatbubbles", ["说", "会", "读", "写", "听", "能", "一点儿", "字", "和", "五"]),
    ("今天几号？", "Огноо", "Нэгж 7 · Огноо, долоо хоног (今天)", "time", ["今天", "号", "月", "星期", "明天", "昨天", "年", "日", "六", "七"]),
    ("我想喝茶", "Хоол хүсэл", "Нэгж 8 · Идэх, уух (想/喝)", "cafe", ["想", "喝", "茶", "杯子", "水", "吃", "米饭", "菜", "苹果", "水果"]),
    ("你儿子在哪儿工作？", "Ажил байршил", "Нэгж 9 · Ажил, байршил (在)", "business", ["在", "工作", "医院", "商店", "后面", "前面", "里面", "上", "下", "八"]),
    ("我能坐这儿吗？", "Зөвшөөрөл", "Нэгж 10 · Тоотой асуулт ба зөвшөөрөл (吗)", "hand-left", ["坐", "这儿", "那儿", "桌子", "椅子", "书", "些", "本", "九", "十"]),
    ("现在几点？", "Цаг хугацаа", "Нэгж 11 · Цаг, хуваарь (现在)", "alarm", ["现在", "点", "分钟", "时候", "上午", "下午", "中午", "回", "做", "打电话"]),
    ("明天天气怎么样？", "Цаг агаар", "Нэгж 12 · Цаг агаар (天气)", "cloud", ["天气", "怎么样", "太", "热", "冷", "下雨", "大", "小", "多", "少"]),
    ("他在学做中国菜呢", "Суралцах", "Нэгж 13 · Одоогийн үйлдэл (呢)", "book", ["学习", "呢", "喜欢", "爱", "看", "电影", "电视", "电脑", "东西", "零"]),
    (
        "她买了不少衣服",
        "Дэлгүүр",
        "Нэгж 14 · Худалдан авалт, тоо (买/了)",
        "cart",
        ["买", "了", "衣服", "钱", "块", "多少", "个", "漂亮", "一", "二", "三", "没", "没有", "有", "睡觉"],
    ),
    ("我是坐飞机来的", "Аялал", "Нэгж 15 · Аялал, тээвэр (飞机)", "airplane", ["飞机", "来", "去", "出租车", "火车", "住", "家", "北京", "怎么", "都"]),
]

WORD_EXAMPLES: Dict[str, Tuple[str, str, str]] = {
    "吗": ("你是学生吗？", "Nǐ shì xuésheng ma?", "Chi oyutan uu?"),
    "不客气": ("不客气！", "Bú kèqi!", "Zügeer!"),
    "对不起": ("对不起，我来晚了。", "Duìbuqǐ, wǒ lái wǎn le.", "Uuchlaarai, bi hojuu irsen."),
    "没关系": ("没关系。", "Méi guānxi.", "Zügeer."),
    "请": ("请坐。", "Qǐng zuò.", "Suugaarai."),
    "同学": ("同学们好。", "Tóngxué men hǎo.", "Angiin naizdaa sain uu?"),
    "也": ("我也是学生。", "Wǒ yě shì xuésheng.", "Bi bas oyutan."),
    "们": ("我们去学校。", "Wǒmen qù xuéxiào.", "Bid surguulid ochloo."),
    "的": ("这是我的书。", "Zhè shì wǒ de shū.", "Ene minii nom."),
    "叫": ("我叫李明。", "Wǒ jiào Lǐ Míng.", "Namaig Li Ming gedeg."),
    "什么": ("你叫什么名字？", "Nǐ jiào shénme míngzi?", "Chinii ner yuu ve?"),
    "名字": ("他的名字很好。", "Tā de míngzi hěn hǎo.", "Tuunii ner sain."),
    "认识": ("很高兴认识你。", "Hěn gāoxìng rènshi nǐ.", "Chamtai taniltsand bayartai."),
    "高兴": ("我很高兴。", "Wǒ hěn gāoxìng.", "Bi mash bayartai."),
    "哪": ("你是哪国人？", "Nǐ shì nǎ guó rén?", "Chi als ulsyn hün be?"),
    "国": ("中国很大。", "Zhōngguó hěn dà.", "Hyatad uls tom."),
    "很": ("天气很冷。", "Tiānqì hěn lěng.", "Tsag agaar mash hüiten."),
    "这": ("这是我的妈妈。", "Zhè shì wǒ de māma.", "Ene minii eej."),
    "那": ("那是我爸爸。", "Nà shì wǒ de bàba.", "Ter minii aav."),
    "谁": ("他是谁？", "Tā shì shéi?", "Ter hen be?"),
    "爸爸": ("我爸爸很忙。", "Wǒ bàba hěn máng.", "Minii aav mash zavgui."),
    "妈妈": ("妈妈在家。", "Māma zài jiā.", "Eej gereetee."),
    "女儿": ("我有一个女儿。", "Wǒ yǒu yí ge nǚ'ér.", "Nadad neg ohin baina."),
    "儿子": ("他儿子七岁。", "Tā érzi qī suì.", "Tuunii hüü doloon nastai."),
    "先生": ("王先生很好。", "Wáng xiānsheng hěn hǎo.", "Aga Wang mash sain."),
    "小姐": ("李小姐在北京。", "Lǐ xiǎojiě zài Běijīng.", "Li hatagtai Beejingd."),
    "朋友": ("他是我的朋友。", "Tā shì wǒ de péngyou.", "Ter minii naiz."),
    "医生": ("妈妈是医生。", "Māma shì yīshēng.", "Eej emch."),
    "哪儿": ("你去哪儿？", "Nǐ qù nǎr?", "Chi haasha yavah ve?"),
    "学校": ("我在学校学习。", "Wǒ zài xuéxiào xuéxí.", "Bi surguulid suraltsana."),
    "汉语": ("我会说汉语。", "Wǒ huì shuō Hànyǔ.", "Bi hyatadaar yarij chaddag."),
    "今年": ("今年我二十岁。", "Jīnnián wǒ èrshí suì.", "Ene jil bi hoyor nastai."),
    "几": ("现在几点？", "Xiànzài jǐ diǎn?", "Odoo hed tsag ve?"),
    "岁": ("你几岁？", "Nǐ jǐ suì?", "Chi hed nastai ve?"),
    "多大": ("你多大？", "Nǐ duō dà?", "Chi hed nastai ve?"),
    "想": ("我想喝茶。", "Wǒ xiǎng hē chá.", "Bi tsai uumaar baina."),
    "杯子": ("一杯水。", "Yì bēi shuǐ.", "Neg ayaga us."),
    "米饭": ("我喜欢米饭。", "Wǒ xǐhuan mǐfàn.", "Bi budatai hool dortoi."),
    "在": ("我在家。", "Wǒ zài jiā.", "Bi gereetei."),
    "工作": ("他在医院工作。", "Tā zài yīyuàn gōngzuò.", "Ter emnellegt ajillana."),
    "坐": ("请坐。", "Qǐng zuò.", "Suugaarai."),
    "这儿": ("我在这儿。", "Wǒ zài zhèr.", "Bi end baina."),
    "现在": ("现在八点半。", "Xiànzài bā diǎn bàn.", "Odoo naim gantshan."),
    "天气": ("今天天气怎么样？", "Jīntiān tiānqì zěnmeyàng?", "Önöödör tsag agaar yaamar baina?"),
    "学习": ("他喜欢学习。", "Tā xǐhuan xuéxí.", "Ter suraltsmagd dostoi."),
    "呢": ("你呢？", "Nǐ ne?", "Chi yaamar baina?"),
    "喜欢": ("我喜欢看电视。", "Wǒ xǐhuan kàn diànshì.", "Bi televis üzehd dortoi."),
    "买": ("我买了一个苹果。", "Wǒ mǎi le yí ge píngguǒ.", "Bi neg alim awsan."),
    "了": ("他来了。", "Tā lái le.", "Ter irsen."),
    "钱": ("我没有钱。", "Wǒ méiyǒu qián.", "Nadad mönög baihgüi."),
    "飞机": ("我坐飞机去北京。", "Wǒ zuò fēijī qù Běijīng.", "Bi ongotsoor Beejing yavna."),
    "怎么": ("你怎么去学校？", "Nǐ zěnme qù xuéxiào?", "Chi yaaj surguuld ochdog ve?"),
    "都": ("我们都在家。", "Wǒmen dōu zài jiā.", "Bid bugd gereetei."),
    "没": ("他没去北京。", "Tā méi qù Běijīng.", "Ter Beejing yavsangui."),
    "没有": ("我没有时间。", "Wǒ méiyǒu shíjiān.", "Nadad tsag baihgüi."),
    "有": ("我有一本书。", "Wǒ yǒu yì běn shū.", "Nadad neg nom baina."),
    "睡觉": ("我要睡觉。", "Wǒ yào shuìjiào.", "Bi unthmaar baina."),
    "三": ("一二三四五。", "Yī èr sān sì wǔ.", "Neg hoyor guran duruw tavan."),
}


def example_triple_for(hanzi: str) -> Optional[Tuple[str, str, str]]:
    return WORD_EXAMPLES.get(hanzi)
